travis:
  secure:
    BINSTAR_TOKEN: HAP7Z3ESK3N5x1YZj7Z+RP3geX5UbyVRaVI5uW7xa4RzPyHC/PLm4dCqMFVg6GomXLPWTp+vgT5GcvM3OBBvOs2kb0s7LLvprBbSMNNhx5Za8nhYdlHv+yS5X894mxPLdNvKzH0IrpZQwYEH7AAKPE/J1hEzJOTIoIPTD9onhO83yNq7eb6SVornRilrbJYBHDoHh7LSXjBZACLfGZce3nZSqmeJv1s9jlkpxaBzKJ6fsQ3pAFW0RLI8QPpDu7X9e39DDkfK+w6NXllbVm5+SY0nhtiCfoSQvj4216A/+Fcg5G1QDR0TjY857vSnil/3kJmfnfIl6wCOo9fFePBc4zDwa42ojHzEUBYXTk5pEG9rY4t8j6Zn8jZ2j48I0YJhFq5lUG1JAoRblCBdiez9lxM35BXQpQKg4bkCJU41Y7b4ue4zOMeHGE7R6HGytf2Rh8Mj+mFx3qF+HtEJ5uRvNmdrZ+Y2Xt6ewZbon2Xez/v8pkiHrhpGFH3YtxmnjgprLL2VkaA59gDJ9plc+xUSL1AAb4KUzp4TFlbmIDrawCTB/qryP5mUyZrg1QkG/Z9vzm/vhI9nDluZ5LsBLhIREx9RRPsZ1kwjYd7bQ8/7cmNBjl80SWkyBusj5tWju3YXbEE//i0GayJCYBEAy+lQLsOVAb985u61ZLQypcYhsIo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
